--liquibase formatted sql

-- changeset byorck:1
CREATE TABLE recommendations
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   UUID         NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    product_text TEXT,
    CONSTRAINT uk_recommendations_product_id UNIQUE (product_id)
);
COMMENT ON TABLE recommendations IS 'Таблица с рекомендациями продуктов';
COMMENT ON COLUMN recommendations.product_id IS 'Уникальный идентификатор продукта (UUID)';
COMMENT ON COLUMN recommendations.product_name IS 'Название продукта, связанного с рекомендацией';
COMMENT ON COLUMN recommendations.product_text IS 'Описание продукта рекомендации';

-- changeset byorck:2
CREATE TABLE queries
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query              TEXT    NOT NULL,
    negate             BOOLEAN NOT NULL DEFAULT FALSE,
    recommendations_id BIGINT  NOT NULL,
    CONSTRAINT fk_queries_recommendations
        FOREIGN KEY (recommendations_id) REFERENCES recommendations (id) ON DELETE CASCADE
);
COMMENT ON TABLE queries IS 'Таблица условий (запросов), составляющих динамические правила рекомендаций';
COMMENT ON COLUMN queries.query IS 'Тип или название условия (типа запроса) в правиле, например USER_OF, ACTIVE_USER_OF и т.д.';
COMMENT ON COLUMN queries.negate IS 'Флаг логического отрицания для условия (true - условие должно не выполняться)';
COMMENT ON COLUMN queries.recommendations_id IS 'Внешний ключ на рекомендацию, к которой относится это правило';

-- changeset byorck:3
CREATE TABLE query_arguments
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_id BIGINT NOT NULL,
    argument TEXT   NOT NULL,
    CONSTRAINT fk_query_arguments_queries
        FOREIGN KEY (query_id) REFERENCES queries (id) ON DELETE CASCADE
);
COMMENT ON TABLE query_arguments IS 'Таблица параметров (аргументов) каждого условия в динамическом правиле';
COMMENT ON COLUMN query_arguments.query_id IS 'Внешний ключ на условие из таблицы queries';
COMMENT ON COLUMN query_arguments.argument IS 'Значение аргумента для данного условия (например, тип продукта, тип транзакции, тип сравнения, и т.п.)';

-- changeset byorck:4
CREATE TABLE statistics
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id BIGINT  NOT NULL,
    count   BIGINT NOT NULL DEFAULT 0,
        CONSTRAINT fk_statistics_recommendations
        FOREIGN KEY (recommendation_id) REFERENCES recommendations (id) ON DELETE CASCADE
);
COMMENT ON TABLE statistics IS 'Таблица для сбора статистики срабатывания правил рекомендаций';
COMMENT ON COLUMN statistics.id IS 'Собственный уникальный ID';
COMMENT ON COLUMN statistics.recommendation_id IS 'Внешний ключ на recommendations.product_id с каскадным удалением';
COMMENT ON COLUMN statistics.count IS 'Счётчик статистики';